### ISSUE TITLE
Can not open keysight mux5g visa addr:  TCPIP0::10.140.129.49::56002::socket

### ISSUE THREAD

**Issue by tongtianyu** [pyvisa/pyvisa-py#224]
Can not open keysight mux5g visa addr:  TCPIP0::10.140.129.49::56002::socket

To Reproduce
--------------
1. Input addr: TCPIP0::10.140.129.49::56002::socket
2. 
rm=visa.ResourceManager('@py')
rm.open_resource(addr)
3. See error
  File "D:\Python36\lib\site-packages\pyvisa\highlevel.py", line 1710, in open_resource
    resource_pyclass = self._resource_classes[(info.interface_type, info.resource_class)]
AttributeError: 'int' object has no attribute 'interface_type'

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\pyvisa\rname.py", line 185, in from_string
    rn = subclass.from_parts(*parts)
  File "D:\Python36\lib\site-packages\pyvisa\rname.py", line 307, in from_parts
    raise ValueError('too many parts')
ValueError: too many parts

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\pyvisa\highlevel.py", line 1039, in parse_resource_extended
    parsed = rname.parse_resource_name(resource_name)
  File "D:\Python36\lib\site-packages\pyvisa\rname.py", line 190, in from_string
    resource_name, ex)

**Comment by MatthieuDartiailh** [comment]
You hit a weird combination that could give a better error message. The correct address is: `TCPIP0::10.140.129.49::56002::SOCKET`, `SOCKET` in all caps. Because you put in lower case the system assumed that you did not specify the resource type and added `INSTR` leading to having too many components in the address.
