### ISSUE TITLE
unpack exception when reading

### ISSUE THREAD

**Issue by fgr1986** [pyvisa/pyvisa-py#291]
To Reproduce
--------------
RPI with raspbian 64b, Rigol DG1062Z connceted.

```
import pyvisa as visa

rm = visa.ResourceManager()
m = rm.open_resource('USB0::6833::1602::DG1ZA175203657::0::INSTR') 
m.write_termination = '\n'
m.read_termination = '\n'
m.query('*IDN?')
```

Data in `resp` (edited `usbtmc.py` to see the issue)
```
b'\x02\x02\xfd\x005\x00\x00\x00\x01\x00\x00\x00Rigol Technologies,DG1062Z,DG1ZA175203657,00.01.08  ' 
b'\n\x00'

```
Error:
```

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    m.query('*IDN?')
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa/resources/messagebased.py", line 644, in query
    return self.read()
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa/resources/messagebased.py", line 486, in read
    message = self._read_raw().decode(enco)
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa/resources/messagebased.py", line 442, in _read_raw
    chunk, status = self.visalib.read(self.session, size)
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa_py/highlevel.py", line 512, in read
    data, status_code = self.sessions[session].read(count)
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa_py/usb.py", line 149, in read
    return self._read(
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa_py/sessions.py", line 793, in _read
    current = reader()
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa_py/usb.py", line 133, in _usb_reader
    return self.interface.read(count)
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa_py/protocols/usbtmc.py", line 466, in read
    response = BulkInMessage.from_bytes(resp)
  File "/home/pi/miniforge3/envs/sitesting/lib/python3.8/site-packages/pyvisa_py/protocols/usbtmc.py", line 113, in from_bytes
    msgid, btag, btaginverse = struct.unpack_from("BBBx", data)
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 2)

```

**Output of `pyvisa-info`**

```

Machine Details:
   Platform ID:    Linux-5.4.72-v8+-aarch64-with-glibc2.17
   Processor:      

Python:
   Implementation: CPython
   Executable:     /home/pi/miniforge3/envs/sitesting/bin/python3.8
   Version:        3.8.6
   Compiler:       GCC 9.3.0
   Bits:           64bit
   Build:          Nov 27 2020 19:00:52 (#default)
   Unicode:        UCS4

PyVISA Version: 1.11.3

Backends:
   ivi:
      Version: 1.11.3 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.5.1
      ASRL INSTR: Available via PySerial (3.5)
      USB INSTR: Available via PyUSB (1.1.0). Backend: libusb1
      USB RAW: Available via PyUSB (1.1.0). Backend: libusb1
      TCPIP INSTR: Available 
      TCPIP SOCKET: Available 
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of funcionality.
         No module named 'gpib'


```

**Comment by MatthieuDartiailh** [comment]
This looks like a Rigol mis implementation of USBTMC.We already have some workaround for some issues. I am unlikely to have time to look into this before next year. If you want to dive more, you can try to figure out why the from_quirky method is not called and if going through it would help.
