### ISSUE TITLE
Add support for flush of more resource types

### ISSUE THREAD

**Issue by dkriegner** [pyvisa/pyvisa-py#348]
Currently support for flushing input and output buffers is only implemented for serial connections. 
The original pull request (#208) mentions that it should be possible to extend this support to TCPIP and GPIB connections. 
Can this support be expected to more connection types?

Attempting to use `flush` currently raise a `NotImplementedError`

To Reproduce
--------------
Steps to reproduce the issue:
Execute the following code:
```
import pyvisa
rm = pyvisa.ResourceManager()
test = rm.open_resource("TCPIP::127.0.0.1::8080::SOCKET")
test.flush(pyvisa.constants.BufferOperation.discard_read_buffer)
```
It will raise:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dk/.local/lib/python3.10/site-packages/pyvisa/resources/messagebased.py", line 797, in flush
    self.visalib.flush(self.session, mask)
  File "/home/dk/.local/lib/python3.10/site-packages/pyvisa_py/highlevel.py", line 222, in flush
    return self.handle_return_value(session, sess.flush(mask))
  File "/home/dk/.local/lib/python3.10/site-packages/pyvisa_py/sessions.py", line 439, in flush
    raise NotImplementedError
NotImplementedError
```

**Output of `pyvisa-info`**
Likely irrelevant, but here it is:
```
$ pyvisa-info                     
Machine Details:
   Platform ID:    Linux-6.1.6-gentoo-dist-x86_64-12th_Gen_Intel-R-_Core-TM-_i7-1265U-with-glibc2.36
   Processor:      12th Gen Intel(R) Core(TM) i7-1265U

Python:
   Implementation: CPython
   Executable:     /usr/bin/python3.10
   Version:        3.10.9
   Compiler:       GCC 12.2.1 20221008
   Bits:           64bit
   Build:          Dec 16 2022 08:30:26 (#main)
   Unicode:        UCS4

PyVISA Version: 1.13.0

Backends:
   ivi:
      Version: 1.13.0 (bundled with PyVISA)
      Binary library: Not found
   py:
      Version: 0.6.0
      ASRL INSTR: Available via PySerial (3.5)
      USB INSTR:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      USB RAW:
         Please install PyUSB to use this resource type.
         No module named 'usb'
      TCPIP INSTR: Available 
      VICP INSTR: Available 
      TCPIP SOCKET: Available 
      GPIB INSTR:
         Please install linux-gpib (Linux) or gpib-ctypes (Windows, Linux) to use this resource type. Note that installing gpib-ctypes will give you access to a broader range of funcionality.
         No module named 'gpib'
   sim:
      Version: 0.5.1
      Spec version: 1.1
```

**Comment by MatthieuDartiailh** [comment]
Feel free to make a PR in that direction. I do not have the bandwidth to address this ATM.
