### ISSUE TITLE
Serial VISA device fails to open: TypeError: __init__() got an unexpected keyword argument 'writeTimeout'

### ISSUE THREAD

**Issue by fake-name** [pyvisa/pyvisa-py#75]
On Ubuntu 14.04, fresh install:
`pip3 install pyvisa pyvisa-py pyserial`

```
>>> import visa
>>> rm = visa.ResourceManager("@py")
>>> rm.list_resources()
('ASRL/dev/ttyUSB0::INSTR',)
>>> dev = rm.open_resource(rm.list_resources()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/pyvisa/highlevel.py", line 1644, in open_resource
    res.open(access_mode, open_timeout)
  File "/usr/local/lib/python3.4/dist-packages/pyvisa/resources/resource.py", line 203, in open
    self.session, status = self._resource_manager.open_bare_resource(self._resource_name, access_mode, open_timeout)
  File "/usr/local/lib/python3.4/dist-packages/pyvisa/highlevel.py", line 1601, in open_bare_resource
    return self.visalib.open(self.session, resource_name, access_mode, open_timeout)
  File "/usr/local/lib/python3.4/dist-packages/pyvisa-py/highlevel.py", line 191, in open
    sess = cls(session, resource_name, parsed)
  File "/usr/local/lib/python3.4/dist-packages/pyvisa-py/sessions.py", line 184, in __init__
    self.after_parsing()
  File "/usr/local/lib/python3.4/dist-packages/pyvisa-py/serial.py", line 68, in after_parsing
    self.interface = cls(port=self.parsed.board, timeout=2000, writeTimeout=2000)
TypeError: __init__() got an unexpected keyword argument 'writeTimeout'

```

**Comment by fake-name** [comment]
Looking at the pyserial docs, `writeTimeout` has been renamed to `write_timeout`.

**Comment by fake-name** [comment]
Oh, as an aside, is there a reason the timeout member is in milliseconds, rather then the float seconds value that's used in pyserial? It basically only serves to be very confusing as it is.
